### ISSUE TITLE
Signal-Windows crashes when the websocket server closes the connection

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#1]
tldr: nothing we can fix or workaround, we have to wait for a new System.Net.WebSockets.Client release.

https://github.com/dotnet/corefx/issues/17317

Stacktrace:
```
System.Exception: Exception from HRESULT: 0x80072EE2
   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()
   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
```

**Comment by Trolldemorted** [comment]
I have created an issue asking for a fixed WebSockets.Client release, maybe they will do it.

https://github.com/dotnet/corefx/issues/24802

**Comment by Trolldemorted** [comment]
Looks like MS is actually moving forward!

https://github.com/dotnet/corefx/pull/25329

**Comment by golf1052** [comment]
Great news!
