### ISSUE TITLE
conversation list items display date even if the conversation is empty

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#100]
We store a 0 in the db, so it displays 1/1/1970. We should display no timestamp if it is 0.

**Comment by LauraLaureus** [comment]
I'll take a look at this :)

**Comment by LauraLaureus** [comment]
Is there a way to check this without sign-up? I'm new to UWP but not to C# (I come from WinForm and WPF).

**Comment by Trolldemorted** [comment]
What exactly do you mean with sign-up?

Signing up with the signal server? Not out-of-the-box I am afraid, but the registration should work with any phone number, even landline ones.

**Comment by LauraLaureus** [comment]
So I order to debug I have to sign-up ?

**Comment by Trolldemorted** [comment]
Well you could comment out the networking code, fill the db with dummy data and see what happens, but I think signing up is the easier way.

**Comment by LauraLaureus** [comment]
Do you mind to test it?
My boyfriend's mail was tried to be hacked after contribute to hacktoberfest and give data,  and I don't want to be the next one.

**Comment by SERVCUBED** [comment]
You can try setting the URL in App.xaml.cs to the staging server `https://textsecure-service-staging.whispersystems.org`, but you may get SSL errors. This issue may require contacts who use Signal to test anyway. I'll have a look.

**Comment by Trolldemorted** [comment]
Sure, just send PR and i will have a look.

But what has signal's registration via phone numbers and hacktoberfest got to do with hacked emails?

**Comment by LauraLaureus** [comment]
It's more related to the fact of give easily your data. In events like hacktoberfest is easy to steal data. 
I'm not pointing you but the fact of give vulnerable data in massive events to unknow people/services, that's the reason I'm carefull with my data. 

By the way, thank you of the attention and help you give me :).

**Comment by Trolldemorted** [comment]
closed by 001a14d01e9792f59050dd7a0ff10bcf4010707e
