### ISSUE TITLE
I lost my databases when upgrading to 0.2.2

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#109]
Is windows clearing the LocalCache folder when upgrading an app?

cc @golf1052, @SERVCUBED 

I fear we must go back to `LocalState` and force disable cloud syncs somehow.

**Comment by SERVCUBED** [comment]
I've just upgraded and it kept mine. Is it possible that the store key has changed for you? I've often found that any key or GUID change can mess with things.

**Comment by Trolldemorted** [comment]
Maybe the certification tests deploy S-W with a different key?

Did you build it yourself or use a store distribution?

**Comment by SERVCUBED** [comment]
I've been building without any key as it's not included in the repo and deploying that to all my devices. Yes, it seems very likely that a recent build was deployed with the store key from a certification test rather than the temporary key. I've had that happen to me before.
