### ISSUE TITLE
our session records sometimes grow to unreasonable sizes

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#113]
My libsignal.db is now above 200MB. I think that it is unlikely, but we may have a bug in libsignal-protocol-dotnet.

**Comment by Trolldemorted** [comment]
I have been having a look at my database, it seems like I have way too many ReceiverChains in several sessions. The maximum number should be 5, the session with my girlfriend's phone has got more than 7000.

@golf1052 what was this [todo](https://github.com/golf1052/libsignal-protocol-pcl/blob/master/signal-protocol-pcl/state/SessionState.cs#L246) for? So far i haven't the faintest idea why there are old chains lingering around.

**Comment by golf1052** [comment]
No idea, I hadn't needed to touch that file. That TODO was from one of the older maintainers.

**Comment by Trolldemorted** [comment]
It is indeed a libsignal-protocol issue:

libsignal-protocol-java is updating an element in the list with
```
this.sessionStructure = this.sessionStructure.toBuilder()
                                             .setReceiverChains(chainAndIndex.second(), updatedChain)
                                             .build();
```
so it obviously replaces the element at `chainAndIndex.second()` with `updatedChain`.


libisgnal-protocol-dotnet is using
```
this.sessionStructure.ReceiverChains.Insert((int)chainAndIndex.second(), chain);
```
which inserts `chain` at `chainAndIndex.second()`, but it also shifts *all elements beyond the index to the right*.

This explains the db size and the degrading performance as the sessions age.

**Comment by Trolldemorted** [comment]
Looks like https://github.com/signal-csharp/libsignal-protocol-dotnet/commit/4456cc161e20a2f06ef963e43502b0a909b6d955 and https://github.com/signal-csharp/libsignal-protocol-dotnet/commit/d2635dfa3d436c3a39d62ad4c958fc18779c04b8 solved this.

Shall we roll a new version out? The impact on our message processing speed was huge.
