### ISSUE TITLE
Signal-Windows deadlocks because of excessive .Wait() usage

### ISSUE THREAD

**Issue by signalwindowsisbest** [signal-csharp/Signal-Windows#146]
The unread marking calls create so much noise on the threadpool that scrolling may cause the entire threadpool to deadlock, because all threads are stuck in a .Wait() call.

**Comment by golf1052** [comment]
With our move to async everywhere I believe this can be closed.
@Trolldemorted?

**Comment by Trolldemorted** [comment]
Yeah, blocking the entire pool should no longer be possible
