### ISSUE TITLE
Signal Windows crashes if it's opened twice

### ISSUE THREAD

**Issue by jamoness** [signal-csharp/Signal-Windows#148]
First attempt to open, everything is ok, if I try to open from the main page (while its on background) crashes until you open from the background list. Then if I close it, and then try to open it again it crashes every time I try to open. Need to reset the phone to make it open, but the loop continues, everything ok the first time, etc.

Log is here https://pastebin.com/2hwj9Nd2

**Comment by Trolldemorted** [comment]
There are no crashes in the log. Could it be that we are not crashing, but fail to bring the window into the foreground?

**Comment by jamoness** [comment]
Maybe, even until a message is received and click the notification the app opens.

**Comment by Trolldemorted** [comment]
0.2.13 is making its way through the store, does it work now?

**Comment by jamoness** [comment]
It's working fine now, guess we can close this! Thanks!

**Comment by Trolldemorted** [comment]
:+1: thanks for your report!
