### ISSUE TITLE
Windows Store Invite Link Doesn't Work

### ISSUE THREAD

**Issue by khashyarkh** [signal-csharp/Signal-Windows#152]
I Received the following message:
_Contact who you got this code from. We can't redeem it._

**Comment by Trolldemorted** [comment]
What?! Do they say anything else?

Could you include a screenshot? I will contact the microsoft support with it if the problem persists.

**Comment by khashyarkh** [comment]
![screenshot_5](https://user-images.githubusercontent.com/34171942/40022705-02182f96-57de-11e8-9233-9afac51b1b2f.jpg)

**Comment by Trolldemorted** [comment]
Did you try to redeem in a browser or in the store?

**Comment by khashyarkh** [comment]
through the browser, and just tried it on the Store, and it works there with no problem.

**Comment by Trolldemorted** [comment]
This should work by now. If anyone has problems with the invite link please let us know immediately!
