### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by jamoness** [signal-csharp/Signal-Windows#153]
Can't open the app! Crashes everytime I try it

**Comment by Trolldemorted** [comment]
Sorry to hear you are hit by a crashing bug again!

On which version are you on? 0.2.15?

Did anything unusual happen before the crashing started?

@golf1052 can we open the "export debug log" dialog in the unhandled exception handler?

**Comment by Trolldemorted** [comment]
#154 implements exporting the debug log on crash, shall I ship it @golf1052?

**Comment by Trolldemorted** [comment]
0.2.16 is on the way through the store, it should export the debug log if it crashes.

**Comment by jamoness** [comment]
Got it! Couldn't open again, where the log goes?

**Comment by Trolldemorted** [comment]
It should ask you where to save it (at least it does on my desktop), but apparently that doesn't work for you :(

**Comment by Trolldemorted** [comment]
@golf1052 is there a user-accessible folder to which we can always write on W10M?

**Comment by golf1052** [comment]
When you tap `Export debug log` your phone should prompt you on where you want to save it. The log file will be wherever you save the file.

**Comment by Trolldemorted** [comment]
The bug occurs only in release builds!

By switching from debug to release I can finally reprodu

```
Unhandled exception at 0x00007FFAACBB4004 (mrt100_app.dll) in Signal-Windows.exe: 0xC0000602:  Ein sofortiger Ausnahmefehler ist aufgetreten. Die Ausnahmehandler werden nicht aufgerufen, und der Prozess wird sofort beendet. occurred
```

We now have something like a callstack:
![grafik](https://user-images.githubusercontent.com/10261186/40410388-fd90e3e6-5e6d-11e8-8c94-cec384b89a02.png)

**Comment by Trolldemorted** [comment]
0.2.17 is on the way, is it any better? I rolled back some dependency updates.

**Comment by jamoness** [comment]
No, just doesn't open and can't get the log

**Comment by Trolldemorted** [comment]
I fear my machine where I am building S-W is getting close to its end of life.

0.2.18 is on the way, built on a different machine.

**Comment by jamoness** [comment]
Yes, I'm on 2.17.0.0 just this morning :| do you think I should uninstall?

**Comment by Trolldemorted** [comment]
Nope, wait for 0.2.18, i assume my building machine is going south/acting up/suffering from a .net native compiler bug, so i built 0.2.18 on a different one

**Comment by jamoness** [comment]
Solved! Thanks, finally I opened the app. Great settings page by the way

**Comment by themilkywayisawesome** [comment]
I had the same problem. It worked after uninstalling and then reinstalling the app
