### ISSUE TITLE
Text pointer leaving the text box

### ISSUE THREAD

**Issue by jamoness** [signal-csharp/Signal-Windows#155]
Hi! Maybe this is a similar problem, but can you avoid the pointer leaving the text after sending a message??

ie write message, send it and avoid leaving the text box, maintain the text box active, I think it is better.

**Comment by Trolldemorted** [comment]
Does the text box lose focus when you press the send button on W10 mobile?

On my W10 desktop left-clicking the send button sends the message and restores the focus afterwards.

**Comment by jamoness** [comment]
Lose it for a moment and takes it back, but I think it would be better to never lose it! Is this possible?

**Comment by Trolldemorted** [comment]
Not sure whether that is possible, however we reduced the delay until the box has focus again in 0.2.19.

Is it fast enough, or is it still perceivable that the box loses focus for a brief moment?

**Comment by jamoness** [comment]
It is perceivable, but faster so it's better. Thanks!! Now I don't need to take that little pause to keep writing

**Comment by Trolldemorted** [comment]
@jamoness 0.2.20 is out, the cursor should not leave the text box at all now.

**Comment by jamoness** [comment]
@trolldemorted hey! Thanks for the news!! I've tried it and writing on it is so smooth!! Love it!
