### ISSUE TITLE
Save as pops when message is sent

### ISSUE THREAD

**Issue by jamoness** [signal-csharp/Signal-Windows#156]
The Save As Window pops sometimes after clicking the send message button. I'm not aware of some particular process to make it happen, and after closing the window the app also close.

**Comment by Trolldemorted** [comment]
That happens only on a crash!

We would be happy to see one of these logs.

**Comment by Trolldemorted** [comment]
This could be due to #157, I will tackle it tonight when I'm home.

**Comment by jamoness** [comment]
Here's a log after intentional crash and the second link it's just a normal bug log.



https://pastebin.com/hudCLAV9



https://pastebin.com/Qh47cnTp

**Comment by Trolldemorted** [comment]
I have disabled the automatic export popup in 0.2.19
