### ISSUE TITLE
Windows Store Couldn't Install (Error Code: 0x80070422)

### ISSUE THREAD

**Issue by khashyarkh** [signal-csharp/Signal-Windows#180]
Windows 10 Version: 1709

**Comment by Trolldemorted** [comment]
Sorry that you are hit by a store-related bug again. Where do you get that error message? From the windows store? Could you provide a screenshot?

**Comment by Trolldemorted** [comment]
I saw your issue @[Signal-Desktop](https://github.com/signalapp/Signal-Desktop/issues/2484), does it work if you turn your VPN off?

**Comment by khashyarkh** [comment]
![image](https://user-images.githubusercontent.com/34171942/41777200-cf3a02b8-763f-11e8-8a8e-66229a70e0b0.png)

**Comment by khashyarkh** [comment]
I tried to install without VPN, Since there are no restrictions on Windows Store

**Comment by khashyarkh** [comment]
windows update is turned on btw.
![image](https://user-images.githubusercontent.com/34171942/41777395-69f42ea0-7640-11e8-871b-f314781a86fa.png)

**Comment by Trolldemorted** [comment]
Looks like your windows update service became damaged somehow? Did you try running the troubleshooter? Can you still update to W10 version 1803?

**Comment by khashyarkh** [comment]
unfortunately no, I tried , maybe Windows Update is corrupted, although the OS works fine in general.

**Comment by Trolldemorted** [comment]
I guess the store won't work until windows update does - did you try the usual tricks like whiping its cache and restarting the service?

**Comment by khashyarkh** [comment]
Hello @Trolldemorted , U were right the problem was that Windows Update Service was disabled...
now Signal is installed and working... 

Thanks a Bunch

**Comment by Trolldemorted** [comment]
Awesome! 🎉
