### ISSUE TITLE
newline inserted at the wrong location

### ISSUE THREAD

**Issue by parafoxx** [signal-csharp/Signal-Windows#188]
### Newline is always appended instead of inserted at the cursors location

_steps to reproduce:_ 

select a chat, type something, put the cursor a few words back, enter newline (shift + enter)

_result:_ 

newline is appended at the end of text

_expected:_ 

newline is inserted at the cursors location

**Comment by jongleur1983** [comment]
can't reproduce this on the current master.

**Comment by Trolldemorted** [comment]
Yeah I think we fixed that during a hacktoberfest - thanks!
