### ISSUE TITLE
Sorry to push but how is this going?

### ISSUE THREAD

**Issue by jamoness** [signal-csharp/Signal-Windows#190]
We need some update of the project.

**Comment by Trolldemorted** [comment]
ATM I barely have time to sleep, on saturday we will be hosting an internal CTF contest for students interested in dipping into it security and the saturday after that one is the ruCTFe.

As soon as the ctf madness is over I will have some time for my bachelor thesis (which I probably should be writing instead of hacking stuff) and Signal-Windows. What is the most urgent feature you'd like to see?

**Comment by jamoness** [comment]
I'm glad to hear about you, and that you keep having good projects. Tbh there's a couple of things we'll be glad to get.



*Fix attached documents (can't send anything but text) also can see images only in little thumbnail

*Delete chats and texts

*Fix notifications (late notifications)

**Comment by Trolldemorted** [comment]
What is wrong with sending attachments on your device? Sending arbitrary files should definitely work!

Large image view is under construction in #194.

Unfortunately we can't do too much about late notifications unless OWS decides to send microsoft push messages :(

**Comment by Trolldemorted** [comment]
But if you do the same with an image it works?

**Comment by Trolldemorted** [comment]
What happens if you hit the send button after attaching an attachment? Nothing?

**Comment by jamoness** [comment]
Sorry, no nothing. Appears the name of the file with an "X" and the send button transforms into the attachment button. So I can't press send. When it returns to send button pressing it does nothing.

**Comment by Trolldemorted** [comment]
What device are you using?

**Comment by Tourniquet88** [comment]
I can confirm the same behaviour here too. I tested it with a friend of mine and he can't send any attachments as well. We were using 15254, Lumia 950 XL.

Would be nice to get that fixed.

**Comment by jamoness** [comment]
Late response, I'm in a lumia 650.
