### ISSUE TITLE
Takes forever to load messages

### ISSUE THREAD

**Issue by Aspire1Inspire2** [signal-csharp/Signal-Windows#196]
It took me around half an hour to open the app. It shows loading messages forever in the starting page. 
I have 1000+ messages to load every time it opens on windows.
Is there something that can be done on this?

Thanks.

**Comment by Trolldemorted** [comment]
What do you mean with it shows "loading messages"? Do you receive 1k+ messages every time you close Signal-Windows?

**Comment by Aspire1Inspire2** [comment]
I mean the windows app is trying to retrieve messages from my phone (maybe, that is what I am guessing).
Yes, there are 1k+ messages every time when I close Signal windows. 

Could there be a choice in the settings that let the user disable the "message sync" or "message update" feature that download all the messages from the phone app to the desktop app? 

Most of the time, it is taking too long to wait. It would be awesome to let the user choose whether to enable the feature or not.

**Comment by Aspire1Inspire2** [comment]
Or could there be a setting option that let the user choose how many messages to download/sync every time when the windows-signal opens?

**Comment by Trolldemorted** [comment]
Could you upload a screenshot? Afaik the server queue is limited to 1k messages, so it is unlikely you are receiving more than that.

**Comment by Aspire1Inspire2** [comment]
I timed it this time. It took me around 19 mins to load 1030 messages.
I don't have a screenshot of 1030 messages, but I have one with 1010 messages from just now.

![1010](https://user-images.githubusercontent.com/12798470/51201988-8dec1d80-18cb-11e9-8a86-cebfbc06305e.PNG)

**Comment by Aspire1Inspire2** [comment]
Sometimes I have a lot more messages and it took half an hour for the windows app to load and open up.
Another issue with loading messages is, the windows app keeps refreshing and remind me new messages in the process. See the read circle I made in the screenshot. It also shows this counter in the task bar.

![110](https://user-images.githubusercontent.com/12798470/51202124-fc30e000-18cb-11e9-8e3f-f031c89c1535.PNG)

**Comment by Trolldemorted** [comment]
That's [Signal-Desktop](https://github.com/signalapp/Signal-Desktop), not Signal-Windows! Signal-Windows is a community project for the UWP platform.
