### ISSUE TITLE
AutoCorrect spelling cannot be turned off.

### ISSUE THREAD

**Issue by furoTmark** [signal-csharp/Signal-Windows#197]
In Windows 10 there is a built in auto-correct, but even when this is turned off, the messages are corrected automatically. 
It creates a problem if you have your system in English, but you write messages in another language.

Maybe a SpellCheck.IsEnabled="False" on the TextBox could resolve this problem.

**Comment by Trolldemorted** [comment]
Are you 100% sure you have turned it off? I am using w10 german localization and I don't see autocorrects happen if I use type other languages.

**Comment by furoTmark** [comment]
![image](https://user-images.githubusercontent.com/1783160/51823919-778d8b00-22e9-11e9-846e-e4929c49c7be.png)

I tried writing "lesz" and it was converted automatically to "less", but strangely only the first time, after that it wasn't corrected anymore. If I close and open the application then it happens again.

**Comment by golf1052** [comment]
I confirmed this locally, I've made a change to add a spell check toggle in the settings as there's no way to get the system wide spell check setting.

![image](https://user-images.githubusercontent.com/1903871/52106966-6a9ebf00-25a9-11e9-8a35-c436721392af.png)

**Comment by Trolldemorted** [comment]
Nice! Odd that the different windows localizations behave differently.
