### ISSUE TITLE
Will there be further support for this project?

### ISSUE THREAD

**Issue by ArtMR126** [signal-csharp/Signal-Windows#208]
I really liked your application, and I would like to know if you will continue to develop it?) It has many advantages over the official client, and I would like to have such functions as listening to voice messages, stickers and emoticons, avatars in contacts, and the like. Thank you for your hard work!

**Comment by Trolldemorted** [comment]
I appreciate your support, but unfortunately I am really busy at the moment, and don't have the time for the development of new features at the moment.
