### ISSUE TITLE
Windows store link is now expired

### ISSUE THREAD

**Issue by nikkoaws** [signal-csharp/Signal-Windows#211]
As per the title - clicking on the invite link returns the error "This token has expired and cannot be redeemed."

**Comment by golf1052** [comment]
@Trolldemorted

**Comment by Trolldemorted** [comment]
Sorry for the delay, I am currently working on my master thesis which eats up virtually all me free time

CQ4QC-KPTJV-XP2VT-67J39-7R9QZ
