### ISSUE TITLE
Bad response: 429 when call GetContacts

### ISSUE THREAD

**Issue by hoangatpaygate** [signal-csharp/Signal-Windows#212]
When try to call the GetContacts it returns an exception that Bad response: 429
Please help to verify

**Comment by golf1052** [comment]
I've fixed this with a local build by implementing the "new" contact discovery service. See https://github.com/signal-csharp/libsignal-service-dotnet/issues/37

Need to do some cleanup first though.

**Comment by golf1052** [comment]
Just pushed a commit which fixes this issue, however I'm not going to try and get a release out until https://github.com/signal-csharp/Signal-Windows/issues/218 is added.

**Comment by golf1052** [comment]
CAPTCHA support has been added. Sending and receiving messages has been acting weird for me so I'm going to investigate that next before trying to get a release out.

**Comment by golf1052** [comment]
Signal Windows 0.3.0 is in the store.
