### ISSUE TITLE
Contact color always reset back to original color

### ISSUE THREAD

**Issue by samsoncheong93** [signal-csharp/Signal-Windows#226]
When I start a new chat with contact, a contact color was picked automatically and I do not like the color (purple), so I changed it to blue color, as well as the chat bubble. However everytime I closed and open back the app, the color keep revert back to the original color and it's annoying consider that everytime have to manually keep change the color often. Need this issue to be fixed.

**Comment by ShelbyBoss** [comment]
This [PR](https://github.com/signal-csharp/Signal-Windows/pull/225) fixes this issue

**Comment by golf1052** [comment]
This has been fixed in 0.3.1 which is now in the Microsoft Store.
