### ISSUE TITLE
Image received not loading

### ISSUE THREAD

**Issue by samsoncheong93** [signal-csharp/Signal-Windows#227]
![image](https://user-images.githubusercontent.com/8064977/109921415-cd1d9880-7cf6-11eb-9cd7-1dcced88f61e.png)

I'm having issues where I received that someone send the message to me, but it won't automatically load. Press the download icon and after wait still doesn't load anything yet.

**Comment by golf1052** [comment]
Known issue, see https://github.com/signal-csharp/libsignal-service-dotnet/pull/45 for progress on the fix

**Comment by golf1052** [comment]
This has been fixed in 0.3.1 which is now in the Microsoft Store.
