### ISSUE TITLE
remove disappearing messages when timer runs out

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/Signal-Windows#44]

**Comment by golf1052** [comment]
I've started working on this

**Comment by Trolldemorted** [comment]
Is there a nice way of updating bulks of ids in the messages cache?

**Comment by golf1052** [comment]
I haven't looked into that specifically yet, I've just wired up the ExpiresInSeconds to a DisappearingMessagesManager that will "delete" (haven't gotten the delete actually working yet) messages after they expire.

Also need to see if the Read flag on messages is being set correctly because disappearing messages should be deleted once read, not on receive.

**Comment by Trolldemorted** [comment]
So we have to add a "read" or a "you have to delete this at" timestamp to our messages table, I guess? Or how are you determining the time a message has been read?

**Comment by golf1052** [comment]
Yep I'll need to add a ReadTimestamp, it looks like we're not marking messages as read, we are however updating the last read index on a conversation.

Here is my list on what needs to be updated to delete a message, the list is ordered. Anything missing?

1. Delete message in conversation UI.  
2. Delete message in cache.  
3. Delete attachments in DB.  
4. Delete message in DB.  
5. Update SignalConversation.MessagesCount  
6. Update SignalConversation.LastSeenMessageIndex  
7. Update SignalConversation.LastMessageId

**Comment by Trolldemorted** [comment]
>Yep I'll need to add a ReadTimestamp, it looks like we're not marking messages as read, we are however updating the last read index on a conversation.

Yup, I noticed that the read field is so far not important (and we don't have to do the I/O for every single message), so I just progressed the unread index.

>2. Delete message in cache.

This step is not easy, unfortunately. The caches (OutgoingCache and UnfinishedAttachmentsCache) map the messages' database ids to their containers, and their containers contain the messages' indices for the virtualized collection. Now when you remove a message from the collection, all subsequent messages' containers must be updated, because their index in the conversation is now decreased by 1.

If you have an idea how to abolish the caches completely let me know, I would gladly throw them overboard - they exist only because I found no other way to obtain a reference to a message's UI representation when I have only the db id (i.e. everytime a message has to be updated).

>Also I see we have an FTS table, does that get automatically updated on SignalDBContext changes? Meaning, if I delete a message from ctx.Messages will it also automatically get deleted from the FTS table?

I really don't know, but I assume they don't.

**Comment by golf1052** [comment]
![2018-06-15_01-28-39](https://user-images.githubusercontent.com/1903871/41458464-870c33c6-703b-11e8-9946-afb724a59fb4.gif)

Got cache removal working

**Comment by Trolldemorted** [comment]
> 1. Delete message in conversation UI.
>2. Delete message in cache.

If we land #169 these should be quite easy, the VirtualizedMessagesCollection should just have to
- remove the message from MessageStorage
- remove the message's mapping from DbIdToMessageMap
- fire the appropriate events

However I think we have to do 5, 6 and 7 before notifying the NotifyCollectionChangedEventHandler, otherwise the collection will be in an inconsistent state (because a message was removed but Count does not return the new Count).

Now that I think about it, maybe we should remove the message from the db first? So that it is definitely gone the next time you start S-W?

**Comment by golf1052** [comment]
First commit afe26af30dcca5b57ef2f51a05c099bcd4919241
As mentioned in the commit
- Use at your own risk.
- Messages get fully deleted once their timer is up.
- Messages get deleted as soon as their received, not read. To fix this messages should be added to the DisappearingMessagesManager once they are read.
- Expired messages don't get cleaned up by the background thread when it starts up.
- Expired messages don't get cleaned up when the app starts.

Also need to double check when the other Signal apps start their message countdown to deletion.
- On message receive?
- On message read in app (not notification)?
- Do messages get marked as read if the app home screen is open but a conversation isn't selected yet?

**Comment by golf1052** [comment]
a54296424713ab6985673fc69797fc483e78f568 deletes expired messages on startup. It probably isn't necessary for the background thread to clean up expired messages but I'm not opposed to adding it.
