### ISSUE TITLE
Do not use MainWindow dispatcher everywhere.

### ISSUE THREAD

**Issue by FrayxRulez** [signal-csharp/Signal-Windows#93]
I suggest you to don't use `CoreApplication.MainView.CoreWindow.Dispatcher` due to UWP threading model: every window has its own thread and you'll probably have a nightmare when you'll decide to implement sharing to the app or My People integration.

**Comment by golf1052** [comment]
What is the recommended way of updating the UI without using the Dispatcher?

**Comment by Trolldemorted** [comment]
I think we have to use the dispatchers, but use the right one for each window. However, `CoreApplication.MainView.CoreWindow.Dispatcher` should always be the core window's dispatcher (even if the core window was closed), correct?

**Comment by FrayxRulez** [comment]
I'm quite sure that if the main window is closed `MainView` will be null.
Yes, you need to use the right dispatcher for every view

**Comment by Trolldemorted** [comment]
@FrayxRulez thanks for your suggestion! We now manually track the dispatchers [here](https://github.com/signal-csharp/Signal-Windows/blob/8075ed395c9e78e0a42c41b53c21a49a343a1957/Signal-Windows.Lib/SignalLibHandle.cs).
